USE [master]
GO

/****** Object:  Database [ATPrank]    Script Date: 31.01.2021 20:55:43 ******/
CREATE DATABASE [ATPrank]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ATPrank', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ATPrank.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ATPrank_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ATPrank_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ATPrank].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ATPrank] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ATPrank] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ATPrank] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ATPrank] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ATPrank] SET ARITHABORT OFF 
GO

ALTER DATABASE [ATPrank] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ATPrank] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ATPrank] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ATPrank] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ATPrank] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ATPrank] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ATPrank] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ATPrank] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ATPrank] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ATPrank] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ATPrank] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ATPrank] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ATPrank] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ATPrank] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ATPrank] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ATPrank] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ATPrank] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ATPrank] SET RECOVERY FULL 
GO

ALTER DATABASE [ATPrank] SET  MULTI_USER 
GO

ALTER DATABASE [ATPrank] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ATPrank] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ATPrank] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ATPrank] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ATPrank] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ATPrank] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ATPrank] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ATPrank] SET  READ_WRITE 
GO

